[package]
name = "engula-supreme-unit"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
homepage = "https://engula.com"
repository = "https://github.com/engula/engula"
description = "Supreme unit manages a universe for Engula."

[dependencies]
microunit = "0.1.1"
