[package]
name = "engula"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
homepage = "https://engula.com"
repository = "https://github.com/engula/engula"
description = "A cloud-native storage engine for next-generation data infrastructures."

[dependencies]
clap = "3.0.0-beta.4"
microunit = "0.1.0"
