value_size = 100
num_entries = 10000
num_put_tasks = 100
num_get_tasks = 10
# journal_url = "http://127.0.0.1:10001"
# storage_urls = ["http://127.0.0.1:10002"]
# manifest_url = "http://127.0.0.1:10003"
# compaction_url = "http://127.0.0.1:10004"

# [aws]
# region
# access_key
# secret_access_key

[compute]
num_shards = 4
num_levels = 4
cache_size_mb = 128
num_cache_shards = 1024
memtable_size_mb = 1024
write_channel_size = 1024

[journal]
path = "/tmp/engula/journal"
sync = true
size = 1073741824

[storage]
path = "/tmp/engula/storage"
sst_block_size_kb = 4
row_group_size_mb = 16
