value_size = 100
num_entries = 39000000
num_put_tasks = 5000
num_get_tasks = 200
journal_url = "http://172.31.25.193:10001"
storage_urls = ["http://172.31.25.193:10002"]
manifest_url = "http://172.31.25.193:10003"

# [aws]
# region
# access_key
# secret_access_key

[compute]
num_shards = 4
num_levels = 4
cache_size_mb = 48
num_cache_shards = 1024
memtable_size_mb = 128
write_channel_size = 1024

[journal]
path = "/data1/bench/journal"
sync = true
size = 1073741824

[storage]
path = "/data2/bench/storage"
sst_block_size_kb = 4
row_group_size_mb = 16
