name: Check Code

on: [push, pull_request]

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  check:
    name: Check style
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: clippy, rustfmt
        override: true

    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
